name: track_supreme
description: "Track Supreme Flutter Uygulaması"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Temel Paketler
  image_picker: ^1.1.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  sqflite: ^2.2.8+4
  path: ^1.8.3
  uni_links: ^0.5.1

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.0
  supabase_flutter: ^1.8.0

  # Sosyal Giriş
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
