// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY3NU_7kpU46UiX7iJNc9LsfLCntBshmQ',
    appId: '1:716458102186:web:e324832855e80715dfafd3',
    messagingSenderId: '716458102186',
    projectId: 'track-supreme-26657',
    authDomain: 'track-supreme-26657.firebaseapp.com',
    storageBucket: 'track-supreme-26657.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoUDNxRZjduQPTIcBSkAo_yl_vSswM_Xg',
    appId: '1:716458102186:android:96f8bb75f646b221dfafd3',
    messagingSenderId: '716458102186',
    projectId: 'track-supreme-26657',
    storageBucket: 'track-supreme-26657.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7BoDzFpofFBg5J8WeSNuF-jbeUGsMN8A',
    appId: '1:716458102186:ios:f9581110131b0921dfafd3',
    messagingSenderId: '716458102186',
    projectId: 'track-supreme-26657',
    storageBucket: 'track-supreme-26657.firebasestorage.app',
    androidClientId: '716458102186-rr4hd8846cfhnhog5pejigs97p41qlmh.apps.googleusercontent.com',
    iosClientId: '716458102186-0fmk4r3ard0cevj370gk0q0j55c4kgqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackSupreme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7BoDzFpofFBg5J8WeSNuF-jbeUGsMN8A',
    appId: '1:716458102186:ios:f9581110131b0921dfafd3',
    messagingSenderId: '716458102186',
    projectId: 'track-supreme-26657',
    storageBucket: 'track-supreme-26657.firebasestorage.app',
    androidClientId: '716458102186-rr4hd8846cfhnhog5pejigs97p41qlmh.apps.googleusercontent.com',
    iosClientId: '716458102186-0fmk4r3ard0cevj370gk0q0j55c4kgqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackSupreme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY3NU_7kpU46UiX7iJNc9LsfLCntBshmQ',
    appId: '1:716458102186:web:55ef4b78c94f54fadfafd3',
    messagingSenderId: '716458102186',
    projectId: 'track-supreme-26657',
    authDomain: 'track-supreme-26657.firebaseapp.com',
    storageBucket: 'track-supreme-26657.firebasestorage.app',
  );

}